# Generated by Django 4.2 on 2026-06-19

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BookReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('author', models.CharField(max_length=180)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('finished', 'Finished'), ('paused', 'Paused'), ('want_to_read', 'Want to Read')], default='finished', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional personal rating from 1 to 5.', null=True, validators=[MinValueValidator(1), MaxValueValidator(5)])),
                ('read_date', models.DateField(blank=True, null=True)),
                ('key_takeaway', models.TextField(blank=True, help_text='The main idea you want people to remember.')),
                ('favorite_quote', models.TextField(blank=True)),
                ('reflection', models.TextField(help_text='Your personal thoughts after reading this book.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book Reflection',
                'verbose_name_plural': 'Book Reflections',
                'ordering': ['-read_date', '-created_at'],
            },
        ),
    ]
