# Generated by Django 6.0.6 on 2026-06-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreflection',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Online cover image URL', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='BookQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The quote text')),
                ('explanation', models.TextField(blank=True, help_text='Your thoughts/reflections on this quote', null=True)),
                ('image', models.ImageField(blank=True, help_text='Local image upload for this quote', null=True, upload_to='books/quotes/')),
                ('image_url', models.URLField(blank=True, help_text='Online image URL for this quote', max_length=1000, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this quote')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.bookreflection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
