# Generated by Django 6.0.6 on 2026-06-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the board card')),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image from your computer', null=True, upload_to='pin_interast/boards/')),
                ('cover_url', models.URLField(blank=True, help_text='Or paste an online image URL for the cover', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pin Board',
                'verbose_name_plural': 'Pin Boards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='Optional caption / notes about the pin')),
                ('image', models.ImageField(blank=True, help_text='Upload an image from your computer', null=True, upload_to='pin_interast/pins/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste a direct image URL (JPEG, PNG, WebP…)', max_length=1000, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Original source link (website, article, etc.)', max_length=1000, null=True)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags, e.g. 'design, typography, dark-ui'", max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinterest_pin_id', models.CharField(blank=True, help_text='Pinterest pin ID — set automatically when imported via API', max_length=100, null=True, unique=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='pin_interast.pinboard')),
            ],
            options={
                'verbose_name': 'Pin',
                'verbose_name_plural': 'Pins',
                'ordering': ['-created_at'],
            },
        ),
    ]
