# Generated by Django 6.0.6 on 2026-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_interast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
