# Generated by Django 6.0.6 on 2026-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_interast', '0002_alter_pin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboard',
            name='pinterest_owner_name',
            field=models.CharField(blank=True, help_text='Display name of the Pinterest board owner', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pinboard',
            name='pinterest_username',
            field=models.CharField(blank=True, help_text="Pinterest username of the board owner (e.g. 'nasa')", max_length=100, null=True),
        ),
    ]
