# Generated by Django 5.0.14 on 2026-09-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_interast', '0003_pinboard_pinterest_owner_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinAudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Song / track title', max_length=255)),
                ('artist', models.CharField(default='Santunu Kaysar', help_text='Artist, composer, or creator', max_length=255)),
                ('audio_file', models.FileField(blank=True, help_text='Upload an audio file (MP3, WAV, OGG)', null=True, upload_to='pin_interast/audio/')),
                ('audio_url', models.URLField(blank=True, help_text='Or direct URL to audio file/stream (MP3, etc.)', max_length=1000, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload cover artwork from your computer', null=True, upload_to='pin_interast/music_covers/')),
                ('cover_url', models.URLField(blank=True, help_text='Or direct online image URL for cover artwork', max_length=1000, null=True)),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite in your music list')),
                ('genre', models.CharField(blank=True, default='Lo-Fi / Ambient', help_text='Genre, mood, or style', max_length=100)),
                ('duration', models.CharField(blank=True, default='0:00', help_text="Duration string (e.g. '3:20')", max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the playlist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, help_text='Optional associated pin board', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_tracks', to='pin_interast.pinboard')),
            ],
            options={
                'verbose_name': 'Pin Audio Track',
                'verbose_name_plural': 'Pin Audio Tracks',
                'ordering': ['-is_favorite', 'order', '-created_at'],
            },
        ),
    ]
