# Generated by Django 5.1.7 on 2025-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume/', verbose_name='Resume'),
        ),
    ]
