# Generated by Django 5.1.7 on 2025-04-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_cp_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('project_img', models.ImageField(blank=True, null=True, upload_to='Project_img/', verbose_name='Project_img')),
                ('details', models.TextField(blank=True, max_length=400, null=True, verbose_name='Details')),
            ],
        ),
        migrations.AlterField(
            model_name='cp_log',
            name='details',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Details'),
        ),
    ]
