# Generated by Django 5.1.7 on 2025-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_projects_alter_cp_log_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificate_Title')),
                ('certificate_img', models.ImageField(blank=True, null=True, upload_to=' Certificate_img/', verbose_name=' Certificate_img')),
                ('certificate_details', models.TextField(blank=True, max_length=600, null=True, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Experience Title')),
                ('experience_img', models.ImageField(blank=True, null=True, upload_to='Experience_img/', verbose_name='Experience_img')),
                ('experience_details', models.TextField(blank=True, max_length=600, null=True, verbose_name='Experience_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Book name')),
                ('book_img', models.ImageField(blank=True, null=True, upload_to=' book_img/', verbose_name=' book_img')),
                ('writer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book name')),
                ('movie_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title Two ')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('research_img', models.ImageField(blank=True, null=True, upload_to='Research_img/', verbose_name='Research_img')),
                ('research_details', models.TextField(blank=True, max_length=300, null=True, verbose_name='Research_details')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Details'),
        ),
    ]
