# Generated by Django 5.2 on 2025-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_certifications_experience_hobbies_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, max_length=600, null=True, verbose_name='Comment')),
            ],
        ),
    ]
