# Generated by Django 5.2 on 2025-05-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_connectme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='research_details',
        ),
    ]
