# Generated by Django 5.2.1 on 2025-05-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_remove_interest_research_img_interest_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='url',
        ),
    ]
