# Generated by Django 5.2.1 on 2025-05-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_remove_interest_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
