# Generated by Django 6.0.6 on 2026-06-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Online image URL for the banner', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='BlogPostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Section title / Subheading', max_length=255, null=True)),
                ('content', models.TextField(blank=True, help_text='Section content (supports linebreaks)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Local image upload', null=True, upload_to='blog/sections/')),
                ('image_url', models.URLField(blank=True, help_text='Online image URL', max_length=1000, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this section')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
