# Generated by Django 6.0.6 on 2026-06-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(help_text='e.g. Full Stack Django Developer', max_length=200),
        ),
    ]
