# Generated by Django 5.0.14 on 2026-08-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile or page URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinterest_url',
            field=models.URLField(blank=True, help_text='Pinterest profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter / X profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel or video URL'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('kaggle', 'Kaggle'), ('leetcode', 'LeetCode'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('medium', 'Medium'), ('whatsapp', 'WhatsApp'), ('custom', 'Custom / Website')], default='facebook', max_length=50)),
                ('label', models.CharField(blank=True, help_text="Display label (e.g. 'Facebook Page', 'Pinterest Art')", max_length=100)),
                ('url', models.URLField(help_text='Full link URL')),
                ('icon_name', models.CharField(blank=True, help_text='Custom Ionicon name (leave blank to auto-detect from platform choice)', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(blank=True, help_text='Link to profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
