# Generated by Django 5.0.14 on 2026-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link title (e.g. Daizzy)', max_length=60)),
                ('url', models.URLField(help_text='Target external or internal URL')),
                ('icon_name', models.CharField(blank=True, help_text='Ionicon name e.g. sparkles-outline, globe-outline, open-outline, rocket-outline', max_length=60)),
                ('open_in_new_tab', models.BooleanField(default=True, help_text='Open in a new browser tab')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Custom Nav Link',
                'verbose_name_plural': 'Custom Nav Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='daizzy_url',
            field=models.URLField(blank=True, help_text='Daizzy external link URL'),
        ),
    ]
